### ISSUE TITLE
A very fatal error in implementation

### ISSUE THREAD

**Issue by thuwzy** [THUDM/tdgia#1]
In `tdgia.py`, we find that the surrogate model list is equal to evaluation model list, which means that you are conducting white box attack, instead of black box attack

**Comment by xz-keg** [comment]
It serves as a choice of surrogate model that allows the user to use any model as surrogate models. 

In experiments we are reporting results using GCN only, while evaluation is under a combination of ALL models. 

Also, for each model, the surrogate models and evaluation models are trained on different runs, noted by 0 and 1.  So even if you choose to use a surrogate model and evaluate on the same model name, it is not "white box attack".

**Comment by thuwzy** [comment]
I see. Could you please specify the line of code in `tdgia.py` where you load evaluation model denoted by '1'? I run your code and found that the model are also evaluated on '0', if I make no modification.

**Comment by xz-keg** [comment]
Please look at line 200 on GIA_evaluate.py.
``
   dir=name+"_"+args.dataset+"/1"
``

Please note that during training it will always output the white box  attack result on surrogate model as reference, however you need to collect the final attack nodes and features and run ``GIA_evaluate.py`` to figure out the final result on multiple models.
