### ISSUE TITLE
关于节点选取和连接的疑问

### ISSUE THREAD

**Issue by panicpan2000** [THUDM/tdgia#2]
你好。我最近开始接触图注入攻击领域，阅读了你们的论文和代码，但是我不太确定在节点选取和连接边方法的理解是否正确。
一、看起来目标节点就是测试集的全部节点吗，或是会扩展至他的K阶邻居包括不是测试集的节点？
二、大体上我感觉扰动边的生成倾向于将注入节点连接低度的目标节点，但我不太明白具体生成过程。
我对此的理解是对每个目标节点计算得分，这个得分与节点的度和预测值相关（真实标签对应的值？第二大的值？），tdgia.py def generateaddon（）中score=culabels[it][label]+2，为何要+2？
然后选取得分高的节点（因为注入节点*扰动边的数量小于目标节点的数量，所以可以直接取前者数量个已排序的目标节点？），
然后根据节点标签将被选的目标节点分成注入节点数量的组，分别与之连接？

**Comment by xz-keg** [comment]
您好。
1：在实验中是这样的，欢迎对扩展到邻居的情况进行研究。
2：也可以写成加权平均的形式，两者是等价的。

**Comment by panicpan2000** [comment]
谢谢解答，祝工作顺利
