### ISSUE TITLE
adj.row，AttributeError: row not found

### ISSUE THREAD

**Issue by Chenjiangwen** [THUDM/tdgia#4]
您好！在运行 tdgia.py 时出现报错：

Traceback (most recent call last):
  File "tdgia.py", line 495, in <module>
    thisadd,adj_new=generateaddon(prlabel,curlabels,adj,total,total+num,testindex,sconnect=args.connections_self,addmax=addmax,num_classes=num_classes,connect=args.max_connections,strategy=args.strategy)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tdgia.py", line 246, in generateaddon
    adj.row=np.hstack([adj.row,newedgesx])
                       ^^^^^^^
  File "D:\app\Anaconda\Lib\site-packages\scipy\sparse\_base.py", line 771, in __getattr__
    raise AttributeError(attr + " not found")
AttributeError: row not found

**Comment by xz-keg** [comment]
Have you trained GNNs first?

**Comment by Chenjiangwen** [comment]
> Have you trained GNNs first?
我在ogb_arxiv上训练了rgcn, 得到了rgcn_ogb_arxiv下面的两个文件0和1，然后运行 tdgia.py 出现上面的报错信息。

**Comment by Chenjiangwen** [comment]
> > Have you trained GNNs first?
> > 我在ogb_arxiv上训练了rgcn, 得到了rgcn_ogb_arxiv下面的两个文件0和1，然后运行 tdgia.py 出现上面的报错信息。

这是运行 tdgia.py 所有的输出信息：
D:\app\Anaconda\python.exe D:\mydata\Py_project\tdgia\tdgia.py 
node num: 169343
edge num: 2315598.0
val num: 29799
test num: 48603
feats num: 128
feat range: -1.388865 1.638744
1
34580
tensor([2.2084e-05, 1.5599e-01, 2.2490e-05, 3.4120e-04, 1.0338e-03, 5.1293e-03,
        1.1614e-04, 7.2343e-05, 7.7211e-01, 1.1800e-05, 1.4307e-03, 4.4884e-05,
        6.4725e-06, 7.6741e-04, 6.4657e-06, 1.0122e-04, 5.1396e-05, 6.6073e-06,
        9.7716e-04, 6.2024e-03, 9.4741e-06, 1.2921e-03, 1.4610e-04, 8.3921e-05,
        3.2776e-03, 5.4835e-05, 2.6035e-03, 3.2462e-05, 2.1390e-02, 2.1658e-02,
        7.1738e-06, 9.6088e-05, 6.8850e-06, 6.5477e-06, 7.8590e-04, 1.1191e-04,
        3.1196e-03, 3.8741e-04, 6.8046e-06, 4.7917e-04], device='cuda:0')
[  38.   51.  312.  214.  685.  419.  178.   60.  514.  135.  521.   46.
    2.  199.   30.   56. 1060.   52.   67.  278.  174.   17.  154.  363.
 1037.   77.  314.  513.  602.   26.  465.  167.   66.   70.  381.   13.
  196.  224.  111.  113.]
100 20000
Traceback (most recent call last):
  File "D:\mydata\Py_project\tdgia\tdgia.py", line 495, in <module>
    thisadd,adj_new=generateaddon(prlabel,curlabels,adj,total,total+num,testindex,sconnect=args.connections_self,addmax=addmax,num_classes=num_classes,connect=args.max_connections,strategy=args.strategy)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mydata\Py_project\tdgia\tdgia.py", line 246, in generateaddon
    adj.row=np.hstack([adj.row,newedgesx])
                       ^^^^^^^
  File "D:\app\Anaconda\Lib\site-packages\scipy\sparse\_base.py", line 771, in __getattr__
    raise AttributeError(attr + " not found")
AttributeError: row not found

**Comment by xz-keg** [comment]
What's your scipy version? This thread may be helpful. https://github.com/scipy/scipy/issues/6533

**Comment by Chenjiangwen** [comment]
> What's your scipy version? This thread may be helpful. [scipy/scipy#6533](https://github.com/scipy/scipy/issues/6533)

我的版本是 scipy  [1.11.3]
根据这个您提供的线索 应该是降级scipy的版本至0.18？但是在安装这个版本会出错导致无法安装。

**Comment by Chenjiangwen** [comment]
已解决
![16992365129771699236512259.png](https://fastly.jsdelivr.net/gh/Chenjiangwen/ImageHostingService@main/pic/16992365129771699236512259.png)
